# Generated by Django 3.2.4 on 2021-07-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0002_auto_20210702_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplefiledocument',
            name='subDocument',
            field=models.CharField(default='k', max_length=100),
        ),
        migrations.AddField(
            model_name='singlefiledocument',
            name='subDocument',
            field=models.CharField(default='k', max_length=100),
        ),
        migrations.AlterField(
            model_name='multiplefiledocument',
            name='docFile',
            field=models.FileField(default=None, upload_to='G:\\Media'),
        ),
        migrations.AlterField(
            model_name='multiplefiledocument',
            name='docFile2',
            field=models.FileField(default=None, upload_to='G:\\Media'),
        ),
        migrations.AlterField(
            model_name='singlefiledocument',
            name='docFile',
            field=models.FileField(default=None, upload_to='G:\\Media'),
        ),
    ]
