# Generated by Django 3.2.4 on 2021-07-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0003_auto_20210702_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefiledocument',
            name='docFile',
            field=models.FileField(upload_to='G:\\Mediatest'),
        ),
    ]
