# Generated by Django 3.2.4 on 2021-07-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleFileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subDocument', models.CharField(default='k', max_length=100)),
                ('docFile', models.FileField(default=None, upload_to='G:\\Media')),
                ('docFile2', models.FileField(default=None, upload_to='G:\\Media')),
            ],
        ),
        migrations.CreateModel(
            name='SingleFileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subDocument', models.CharField(default='k', max_length=100)),
                ('docFile', models.FileField(default=None, upload_to='G:\\Media')),
            ],
        ),
    ]
