# Generated by Django 3.2.4 on 2021-07-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplefiledocument',
            name='docFile',
            field=models.FileField(upload_to='G:\\Media'),
        ),
        migrations.AlterField(
            model_name='multiplefiledocument',
            name='docFile2',
            field=models.FileField(upload_to='G:\\Media'),
        ),
        migrations.AlterField(
            model_name='singlefiledocument',
            name='docFile',
            field=models.FileField(upload_to='G:\\Media'),
        ),
    ]
