# Generated by Django 3.2.4 on 2021-07-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleFileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docFile', models.FileField(upload_to='G:\\Media')),
            ],
        ),
        migrations.RenameModel(
            old_name='Document',
            new_name='MultipleFileDocument',
        ),
    ]
